### ISSUE TITLE
Consider [M]+ in khipu building?

### ISSUE THREAD

**Issue by YuanyeChi** [shuzhao-li-lab/khipu#8]
Thanks to Josh and Shujian, I came to realize the ESI source we are using is taking [M+H]+ as molecular ion peak. Maybe we should also consider [M]+ in some situation like NH4+ is injected into mass spec or in other theoratical situations, as well as GC orbitrap data that khipu may be used on?

**Comment by jmmitc06** [comment]
Just to provide more context and clarify a few things, I think the question at that time was if loss of an electron should be considered in our experiments as an ionization mode. From Shujian's input we believe the answer at this time should be no, since this is not a common ionization modality. Bigger picture question is can Khipu handle this case and I believe the answer is yes. You simply need to add a '+' adduct with a mass difference corresponding to losing an electron. 

For GC orbitrap, the main issue is going to be that the mass differences between peaks is not due to adduct formation but rather due to fragmentation since the ionization mode is EI. This will require a 'tolerant' verison of Khipu that will not disregard unknown mass patterns. 

The NH4 situation was dealing with disambiguating the case where we have a compound with an amine NH3 (i.e., M+NH3, that picks up an H would have the same mass as a compound without an amine, M, that picks up an ammonium M+NH4+. Khipu might be able to disambiguate those cases if other adducts are observed, e.g., if you see M+H and M+Na, you would know that the compound has the NH3 group and not the adduct. 

I think we can close this issue if that address your concern.

**Comment by YuanyeChi** [comment]
Thank you very much for explanation! 

The NH4 situation I want to ask is that if the sample itself has NH4+ ion, how could mass spec detect NH4+ since NH4+ cannot be protonated. But thanks to your answer, I realized there is reversible reaction between NH3 and NH4+. So if the sample are biological with existense of water, NH3 and NH4+ are co-existing.

I will close this issue because all my questions are addressed.
